Merge Babylon Map into Babylon Core
Babylon-Development-Victoria-3/Victoria-3-Dev pull request #147
Opened 2023-11-15 15:50 UTC by Emifas

2023-11-16 11:32 UTC, HiddeLekanne requested changes
half reviewed.

2023-11-16 11:32 UTC, HiddeLekanne commented on common/customizable_localization/babylon_localisation.txt
> +			c:YUE = { has_variable = qing_language_conference_local_dialect }
It would be nice if you also check that they exists, to prevent the flooding of errors when the country doesn 't exist

2023-11-16 11:32 UTC, HiddeLekanne commented on common/decisions/qing_decisions.txt
babylon_qing_decision?

2023-11-16 11:32 UTC, HiddeLekanne commented on common/decisions/russia_decisions.txt
Soo what are we doing here exactly? there is already a journal entry je_the_eastern_border. The options layed down here are from je_the_eastern_border_treaty_of_beijing and je_the_eastern_border_russia_chuguchak_protocol. 

You're not overwriting the je_the_eastern_border anywhere, meaning we have these options duplicated.

2023-11-16 11:32 UTC, HiddeLekanne commented on common/dynamic_country_names/TODO_korea.txt
empty file

2023-11-16 11:32 UTC, HiddeLekanne commented on common/dynamic_country_names/danubian_vilayet.txt
This was not added in the tanzimat? jeez

2023-11-16 11:32 UTC, HiddeLekanne commented on common/decisions/russia_decisions.txt
> +			is_player = no
Wait this decision is AI only? why? This makes it useless in multiplayer.

2023-11-16 11:32 UTC, HiddeLekanne commented on common/decisions/russia_decisions.txt
> +		else_if = {
should be first if the costs are lower (because you're basically making the choice for the player, it should be the most optimal possible.

2023-11-16 11:32 UTC, HiddeLekanne commented on common/decisions/russia_decisions.txt
Also you do not change the event russo_chinese.1 anywhere, so the event still assumes qing owns manchuria, not the eastern provinces.

2023-11-16 11:32 UTC, HiddeLekanne commented on common/dynamic_country_names/chinese_viceroyalties.txt
I would prefer a long file called babylon_dynamic_country_names.txt where you put all your changes.

2023-11-16 11:32 UTC, HiddeLekanne commented on common/dynamic_country_names/chinese_viceroyalties.txt
Needs formatting

2023-11-16 11:32 UTC, HiddeLekanne commented on common/dynamic_country_names/danubian_vilayet.txt
Needs formatting

2023-11-16 11:32 UTC, HiddeLekanne commented on common/flag_definitions/babylon_flag_definitions.txt
> +#	}
No commented out code.

2023-11-16 11:32 UTC, HiddeLekanne commented on common/flag_definitions/babylon_flag_definitions.txt
Needs formatting

2023-11-16 11:32 UTC, HiddeLekanne commented on common/government_types/00_babylon_governments.txt
> +}
was this also not defined in the tanzimat? lol. if it is defined then this is duplication

2023-11-16 11:32 UTC, HiddeLekanne commented on common/government_types/00_babylon_governments.txt
> +}
was this also not defined in the tanzimat? lol. if it is defined then this is duplication

2023-11-16 11:32 UTC, HiddeLekanne commented on common/history/characters/bulgaria.txt
why is this not on babylon core already with the tanzimat? :/

2023-11-16 11:32 UTC, HiddeLekanne commented on common/history/countries/bul - bulgaria.txt
This is already in core, wtf is happening.

2023-11-16 11:32 UTC, HiddeLekanne commented on common/history/countries/frs - formosa.txt
formatting

2023-11-16 11:32 UTC, HiddeLekanne commented on common/history/diplomacy/ottoman_subjects.txt
more tanzimat stuff

2023-11-16 11:46 UTC, Emifas commented on common/decisions/russia_decisions.txt
@Danarca needs to explain this as these files were added by him when migrating fragile unity to use script values.

2023-11-16 11:49 UTC, Danarca commented on common/decisions/russia_decisions.txt
Since all of the `china_warlord_explosion` variables was multiplied by 20 I had to include this file to make it 40 instead of 2. 
The only changes here are `var:china_warlord_explosion` >= 40 # Was 2`

Although Kikker raises a good point with the ownership of Manchuria...

2023-11-16 13:01 UTC, Emifas commented on common/dynamic_country_names/TODO_korea.txt
PDX ended up doing what I was going to do - will remove

2023-11-16 13:01 UTC, Emifas commented on common/dynamic_country_names/danubian_vilayet.txt
bulgaria stuff was on here before being migrated to tanzimat. will remove

2023-11-16 13:26 UTC, Emifas commented on common/decisions/russia_decisions.txt
I am checking vanilla and I think this file has been deprecated by vanilla in favour of the je_the_eastern_border? @Danarca

2023-11-16 13:29 UTC, Emifas commented on common/decisions/russia_decisions.txt
Yeah the functionality of the decision was moved to a button in je_the_eastern_border which is in scripted_buttons/04_russia_buttons.txt

2023-11-16 13:57 UTC, Danarca commented on common/decisions/russia_decisions.txt
Alright.. want me to do the switch-around?

2023-11-16 13:58 UTC, Emifas commented on common/decisions/russia_decisions.txt
yes please

2023-11-16 14:43 UTC, Danarca commented on common/decisions/russia_decisions.txt
Done :)

2023-11-17 18:57 UTC, HiddeLekanne commented on localization/english/babylon_qing_l_english.yml
> + warlord_china_criteria:3 "Each of the following will contribute #red 20%#! to the fracturing of [SCOPE.GetRootScope.GetCountry.GetName]: \n- Failing to retake the #BOLD Heavenly Kingdom#!\n- Failing
missing " at the end.

2023-11-17 19:52 UTC, HiddeLekanne reviewed
another partial review....

2023-11-17 19:52 UTC, HiddeLekanne commented on events/babylon_qing_substate_events.txt
formatting

2023-11-17 19:52 UTC, HiddeLekanne commented on events/babylon_qing_substate_events.txt
> +			}
```
set_variable = {
				name = qing_language_conference_majority
				value = {
				    add = var:qing_language_conference_voters_count
				    divide = 2
				    add = 1 
			}
```

2023-11-17 19:52 UTC, HiddeLekanne commented on events/babylon_qing_substate_events.txt
> +			}
Also you need to round it. Use round_variable

2023-11-17 19:52 UTC, HiddeLekanne commented on events/babylon_qing_substate_events.txt
> +				trigger_event = { id = babylon_qing_substates.9 days =  91}
this will vote 91 days later..... is that on purpose?

2023-11-17 19:52 UTC, HiddeLekanne commented on events/babylon_qing_substate_events.txt
> +	}
no testing in pull requst.

2023-11-17 19:52 UTC, HiddeLekanne commented on events/babylon_qing_substate_events.txt
> +babylon_qing_substates.9 = { #Linguistic conference - Vote for a language.
This event needs ai guidance for the options.

2023-11-17 21:05 UTC, Dunnow commented on events/babylon_qing_substate_events.txt
> +				trigger_event = { id = babylon_qing_substates.9 days =  91}
The 91 days is deliberate, the event times out after 3 months and the option selected sets some variables that the next event needs, so I was trying to avoid race conditions by letting a day tick first

2023-11-18 15:53 UTC, HiddeLekanne approved these changes

2023-11-18 15:53 UTC, HiddeLekanne commented on map_data/state_regions/11_east_asia.txt
needs manual formatting

2023-11-18 15:53 UTC, HiddeLekanne commented on common/scripted_buttons/04_russia_buttons.txt
> +			is_player = no
still means this will never be pressed in multiplayer

2023-11-18 16:22 UTC, merged