Imperia west africa rework
Babylon-Development-Victoria-3/Victoria-3-Dev pull request #223
Opened 2024-04-16 23:08 UTC by jikanx2004

2024-04-21 12:48 UTC, HiddeLekanne requested changes

2024-04-21 12:48 UTC, HiddeLekanne commented on common/country_definitions/zzz_imperia_map.txt
> +	capital = STATE_VOLTA
missing closing bracket.

2024-04-21 12:48 UTC, HiddeLekanne commented on common/history/countries/mas - massina.txt
> +	c:MSN	= {
?=

2024-04-21 12:48 UTC, HiddeLekanne commented on common/history/countries/dah - dahomey
> +
unnecessary white space

2024-04-21 12:48 UTC, HiddeLekanne commented on common/history/countries/oyo - oyo.txt
> +
unnecessary white space

2024-04-21 12:48 UTC, HiddeLekanne commented on common/history/countries/sok - sokoto.txt
> +
unnecessary white space (one too many)

2024-04-21 12:48 UTC, HiddeLekanne commented on common/history/countries/ash - ashanti.txt
> +
unnecessary white space

2024-04-21 12:48 UTC, HiddeLekanne commented on common/country_definitions/zzz_imperia_map.txt
> +MOS = {
So mossy i a country without any buildings or army, which seems a bit silly.

2024-04-30 09:36 UTC, HiddeLekanne requested changes

2024-04-30 09:36 UTC, HiddeLekanne commented on common/country_definitions/zzz_imperia_map.txt
> +CAR = {
Why is this added?

2024-04-30 09:36 UTC, HiddeLekanne commented on common/history/military_formations/imperia_military_formations.txt
> +			}
You should at least make it so that the army doesn't get huge penalties by including enough infantry.

2024-05-06 19:04 UTC, HiddeLekanne requested changes
The country (mossi) still has no administrative or economic buildings, are you sure that you want that this way?

2024-05-28 16:15 UTC, jikanx2004 commented
> The country (mossi) still has no administrative or economic buildings, are you sure that you want that this way?

I have fixed the lack of economic biuldings. There was a lack of a real administrative structure as they still used the Medieval system of submission on horse back

2024-05-28 19:40 UTC, HiddeLekanne commented
> > The country (mossi) still has no administrative or economic buildings, are you sure that you want that this way?
> 
> I have fixed the lack of economic biuldings. There was a lack of a real administrative structure as they still used the Medieval system of submission on horse back

You didn't push

2024-05-29 23:04 UTC, jikanx2004 commented
> > > The country (mossi) still has no administrative or economic buildings, are you sure that you want that this way?
> > 
> > 
> > I have fixed the lack of economic biuldings. There was a lack of a real administrative structure as they still used the Medieval system of submission on horse back
> 
> You didn't push

I pushed just now sorry

2024-05-31 14:32 UTC, HiddeLekanne approved these changes

2024-05-31 14:32 UTC, merged