removed spanish units in states they don't own
Babylon-Development-Victoria-3/Victoria-3-Dev pull request #246
Opened 2024-06-02 17:06 UTC by Emifas

2024-06-03 10:06 UTC, Danarca requested changes
![image](https://github.com/Imperia-Development-Victoria-3/Victoria-3-Dev/assets/44327039/dbf6a894-eacc-40d1-80af-8d8f2d714989)
Missing an admiral for the navy, causing these errors; 

`[12:00:49][jomini_script_system.cpp:262]: Script system error!
  Error: fully_mobilize_army effect [ Scope formation cannot be mobilized ]
  Script location: file: common/history/military_deployments/00_imperia_military_deployments.txt line: 10`

`[12:00:49][jomini_script_system.cpp:262]: Script system error!
  Error: teleport_to_front effect [ Cannot teleport scope formation Real Armada EspaÃ±ola (92) to target front Toledo Navarra Front (0) due to:  ]
  Script location: file: common/history/military_deployments/00_imperia_military_deployments.txt line: 11`

In case there's still errors, try placing a `?` sign in front of the `=` in the country tag parts; so for example it might be `c:SPA ?= {`

2024-06-04 09:31 UTC, Danarca approved these changes
There we go, no more errors.

2024-06-04 16:55 UTC, HiddeLekanne requested changes

2024-06-04 16:55 UTC, HiddeLekanne commented on common/history/military_deployments/00_imperia_military_deployments.txt
> +			}
This is not valid code?

2024-06-04 16:55 UTC, HiddeLekanne commented on common/history/military_deployments/00_imperia_military_deployments.txt
> +			}
also you want to still mobilize, just not teleported.

2024-06-04 17:22 UTC, Danarca commented on common/history/military_deployments/00_imperia_military_deployments.txt
> +			}
> you want to still mobilize, just not teleported.

This is vanilla behaviour though for conflicts ongoing at game start? Unless I'm misunderstanding :s

2024-06-04 17:24 UTC, HiddeLekanne commented on common/history/military_deployments/00_imperia_military_deployments.txt
> +			}
nvm I thought it was only teleporting.

2024-06-04 17:24 UTC, HiddeLekanne approved these changes

2024-06-06 15:45 UTC, merged