Imperia workers rights rework
Babylon-Development-Victoria-3/Victoria-3-Dev pull request #319
Opened 2024-10-05 21:35 UTC by Unintuition-Time

Still Pending Final Icons & Tiger Test

2024-10-06 10:30 UTC, HiddeLekanne commented
You can also check the errors here: 
![image](https://github.com/user-attachments/assets/ff0a7a8b-daa6-481a-bc0f-3cc34e2cbb18)

2024-10-06 16:54 UTC, HiddeLekanne requested changes
# THE EVENTS FALLONAR THE EVENTS!

2024-10-13 16:24 UTC, HiddeLekanne approved these changes

2024-10-13 17:00 UTC, HiddeLekanne requested changes

2024-10-13 17:00 UTC, HiddeLekanne commented on common/history/countries/bic - british east india company.txt
Remove all the law_no_workers_rights from history, because they are getting overwritten anyway. This is very bad practice to keep here.

2024-10-13 17:01 UTC, HiddeLekanne commented on common/scripted_effects/00_political_setup.txt
Also remove the no workers from here. They get overwritten anyways.

2024-10-14 08:56 UTC, HiddeLekanne approved these changes

2024-10-19 07:31 UTC, Danarca approved these changes
Not sure if you need my approval Fallonar, but you have it :p

2024-10-19 17:03 UTC, merged