Imperia 1.8 balance patch v1
Babylon-Development-Victoria-3/Victoria-3-Dev pull request #350
Opened 2024-12-27 06:10 UTC by Unintuition-Time

Adding more to it this weekend

2024-12-28 07:02 UTC, Danarca commented on common/defines/imperia_defines.txt
We really need to test this, these are some pretty big changes to migration.

2024-12-28 17:42 UTC, Danarca commented on common/defines/imperia_defines.txt
Wait, actually, the removal just means we go back to vanilla values, right? My dumb morning brain thought this would be akin to straight up deleting those defines from calculations >.<
@Unintuition-Time

2024-12-28 21:42 UTC, HiddeLekanne commented on common/buildings/07_government.txt
> +	required_construction = construction_cost_low
I actually quite like the very_low costs for admin buildings. It is a bit unrealistic for example for healthcare and stuff. But it is an expenditure anyways.

2024-12-29 18:21 UTC, HiddeLekanne commented on common/ideologies/00_ig_ideologies_event.txt
> +		law_laissez_faire = disapprove
order

2024-12-29 18:30 UTC, HiddeLekanne approved these changes

2024-12-29 18:32 UTC, HiddeLekanne requested changes

2024-12-29 18:32 UTC, HiddeLekanne commented on localization/english/imperia_misc_l_english.yml
> + imperia_british_india_mortality_modifier: "Poor India"
Better localisation would be nice?

2024-12-29 18:43 UTC, HiddeLekanne approved these changes

2024-12-29 18:43 UTC, merged